DROP TABLE IF EXISTS  CONFIGURATION;
DROP TABLE IF EXISTS CUSTOM_CONFIG;

CREATE TABLE CONFIGURATION (
  NAME VARCHAR(40),
  VALUE VARCHAR(255),
  PRIMARY KEY (NAME)
);

CREATE TABLE CUSTOM_CONFIG (
  K VARCHAR(40),
  V VARCHAR(255),
  PRIMARY KEY (K)
);

INSERT INTO CONFIGURATION (NAME, VALUE) VALUES ('FOO', 'BAR'), ('TEST', 'TEST');

INSERT INTO CUSTOM_CONFIG (K, V) VALUES ('BAR', 'FOO'), ('test', 'testing123');
